name: Build models & check API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure processed dir + create tiny dataset if none
        shell: bash
        run: |
          set -e
          mkdir -p data/processed
          if compgen -G "data/processed/exoplanets_common_*.parquet" > /dev/null || \
             compgen -G "data/processed/exoplanets_common_*.csv" > /dev/null; then
            echo "Found processed file(s)."
          else
            printf '%s\n' \
              'mission,period_days,duration_hours,depth_ppm,label_3way,system_key' \
              'kepler,10.0,2.5,800.0,confirmed,kepler|KOI-1|10.0' \
              'k2,12.0,2.7,820.0,confirmed,k2|EPIC-1|12.0' \
              'kepler,42.0,5.0,1500.0,candidate,kepler|KOI-2|42.0' \
              'k2,38.0,4.5,1400.0,candidate,k2|EPIC-2|38.0' \
              'tess,3.14,1.2,500.0,fp,tess|TOI-1|3.14' \
              'tess,5.20,1.3,520.0,fp,tess|TOI-2|5.20' \
              > data/processed/exoplanets_common_stub.csv
            echo "Wrote data/processed/exoplanets_common_stub.csv"
          fi

      - name: Prepare features (create preprocessor.pkl / feature_list.json / target_map.json)
        shell: bash
        run: |
          set -e
          if compgen -G "data/processed/exoplanets_common_*.parquet" > /dev/null; then
            INPUT=$(ls -1 data/processed/exoplanets_common_*.parquet | tail -n1)
          else
            INPUT=$(ls -1 data/processed/exoplanets_common_*.csv | tail -n1)
          fi
          echo "Using INPUT=$INPUT"
          python data/prepare_features.py \
            --input "$INPUT" \
            --missions all \
            --target label_3way \
            --drop-invalid yes \
            --outdir models/ \
            --split random \
            --seed 42
          ls -lh models/

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/preprocessor.pkl
            models/feature_list.json
            models/target_map.json
