name: Build models & check API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ensure processed dir + create BIG stub if none
        shell: bash
        run: |
          set -e
          mkdir -p data/processed
          if compgen -G "data/processed/exoplanets_common_*.parquet" > /dev/null || \
             compgen -G "data/processed/exoplanets_common_*.csv" > /dev/null; then
            echo "Found processed file(s) — skipping stub creation."
          else
            OUT=data/processed/exoplanets_common_stub.csv
            echo 'mission,period_days,duration_hours,depth_ppm,label_3way,system_key' > "$OUT"
            # 10 записей confirmed / 10 candidate / 10 fp
            for i in $(seq 1 10); do
              printf 'kepler,%s,2.5,800.0,confirmed,kepler|KOI-%s|%s\n'  "$((10 + i))" "$i" "$((10 + i))" >> "$OUT"
              printf 'k2,%s,4.0,1400.0,candidate,k2|EPIC-%s|%s\n'        "$((30 + i))" "$i" "$((30 + i))" >> "$OUT"
              printf 'tess,%s,1.2,500.0,fp,tess|TOI-%s|%s\n'              "$((3  + i))" "$i" "$((3  + i))" >> "$OUT"
            done
            echo "Wrote $OUT"
          fi

      - name: List models before
        run: ls -lah models || true

      - name: Clear old model artifacts (avoid feature_list mismatch)
        run: |
          rm -f models/feature_list.json models/preprocessor.pkl models/target_map.json || true

      - name: Prepare features (create preprocessor.pkl / feature_list.json / target_map.json)
        shell: bash
        run: |
          set -e
          if compgen -G "data/processed/exoplanets_common_*.parquet" > /dev/null; then
            INPUT=$(ls -1 data/processed/exoplanets_common_*.parquet | tail -n1)
          else
            INPUT=$(ls -1 data/processed/exoplanets_common_*.csv | tail -n1)
          fi
          echo "Using INPUT=$INPUT"
          python data/prepare_features.py \
            --input "$INPUT" \
            --missions all \
            --target label_3way \
            --drop-invalid yes \
            --outdir models/ \
            --split random \
            --seed 42
          echo "Models dir content:"
          ls -lh models || true

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/preprocessor.pkl
            models/feature_list.json
            models/target_map.json
          if-no-files-found: warn
